package views;

import calcExceptions.CalculIncomplet;
import entities.Calcul;
import entities.Calculateur;
import java.util.ArrayList;
import java.util.Iterator;

/*
 * 180712 - Creation
 * Classe vue pour la calculatrice
 */

/**
 *
 * @author Pierre-Etienne Bouchard
 */
public class Calculatrice extends javax.swing.JFrame {

    
    Calcul calcul = new Calcul();
    Calculateur calculateur = new Calculateur();
    
    /**
     * Creates new form Calculatrice
     */
    public Calculatrice() {
        initComponents();
        textHistorique.setLineWrap(true);
        textHistorique.setWrapStyleWord(true); 
    }

       

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupeBoutonOperandes = new javax.swing.ButtonGroup();
        groupeBoutonOperations = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelNomApplication = new javax.swing.JLabel();
        bouton1 = new javax.swing.JButton();
        bouton2 = new javax.swing.JButton();
        bouton3 = new javax.swing.JButton();
        bouton5 = new javax.swing.JButton();
        bouton4 = new javax.swing.JButton();
        bouton6 = new javax.swing.JButton();
        bouton7 = new javax.swing.JButton();
        bouton8 = new javax.swing.JButton();
        bouton9 = new javax.swing.JButton();
        bouton0 = new javax.swing.JButton();
        textOperation = new javax.swing.JTextField();
        boutonAddition = new javax.swing.JButton();
        boutonSoustraction = new javax.swing.JButton();
        boutonMultiplication = new javax.swing.JButton();
        boutonDivision = new javax.swing.JButton();
        boutonCalculer = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelHistorique = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textHistorique = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNomApplication.setText("Calculatrice");

        bouton1.setText("1");
        groupeBoutonOperandes.add(bouton1);
        bouton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton1ActionPerformed(evt);
            }
        });

        bouton2.setText("2");
        groupeBoutonOperandes.add(bouton2);
        bouton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton2ActionPerformed(evt);
            }
        });

        bouton3.setText("3");
        groupeBoutonOperandes.add(bouton3);
        bouton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton3ActionPerformed(evt);
            }
        });

        bouton5.setText("5");
        groupeBoutonOperandes.add(bouton5);
        bouton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton5ActionPerformed(evt);
            }
        });

        bouton4.setText("4");
        groupeBoutonOperandes.add(bouton4);
        bouton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton4ActionPerformed(evt);
            }
        });

        bouton6.setText("6");
        groupeBoutonOperandes.add(bouton6);
        bouton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton6ActionPerformed(evt);
            }
        });

        bouton7.setText("7");
        groupeBoutonOperandes.add(bouton7);
        bouton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton7ActionPerformed(evt);
            }
        });

        bouton8.setText("8");
        groupeBoutonOperandes.add(bouton8);
        bouton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton8ActionPerformed(evt);
            }
        });

        bouton9.setText("9");
        groupeBoutonOperandes.add(bouton9);
        bouton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton9ActionPerformed(evt);
            }
        });

        bouton0.setText("0");
        groupeBoutonOperandes.add(bouton0);
        bouton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton0ActionPerformed(evt);
            }
        });

        boutonAddition.setText("+");
        groupeBoutonOperations.add(boutonAddition);
        boutonAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAdditionActionPerformed(evt);
            }
        });

        boutonSoustraction.setText("-");
        groupeBoutonOperations.add(boutonSoustraction);
        boutonSoustraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSoustractionActionPerformed(evt);
            }
        });

        boutonMultiplication.setText("x");
        groupeBoutonOperations.add(boutonMultiplication);
        boutonMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMultiplicationActionPerformed(evt);
            }
        });

        boutonDivision.setText("/");
        groupeBoutonOperations.add(boutonDivision);
        boutonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDivisionActionPerformed(evt);
            }
        });

        boutonCalculer.setText("=");
        boutonCalculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCalculerActionPerformed(evt);
            }
        });

        jButtonClear.setText("C");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bouton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bouton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bouton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bouton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bouton6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(bouton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boutonAddition, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(boutonSoustraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boutonMultiplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(2, 2, 2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bouton7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bouton0, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(bouton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(bouton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boutonCalculer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(boutonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textOperation, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(labelNomApplication))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelNomApplication)
                .addGap(18, 18, 18)
                .addComponent(textOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton3)
                    .addComponent(bouton1)
                    .addComponent(bouton2)
                    .addComponent(boutonAddition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton5)
                    .addComponent(bouton4)
                    .addComponent(bouton6)
                    .addComponent(boutonSoustraction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton7)
                    .addComponent(bouton8)
                    .addComponent(bouton9)
                    .addComponent(boutonMultiplication))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton0)
                    .addComponent(boutonDivision)
                    .addComponent(boutonCalculer)
                    .addComponent(jButtonClear))
                .addContainerGap())
        );

        labelHistorique.setText("Historique");

        textHistorique.setColumns(20);
        textHistorique.setRows(5);
        jScrollPane1.setViewportView(textHistorique);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelHistorique)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHistorique)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton1ActionPerformed
        calcul.ajouterOperande("1");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_bouton1ActionPerformed

    private void bouton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton2ActionPerformed
        calcul.ajouterOperande("2");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_bouton2ActionPerformed

    private void bouton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton3ActionPerformed
        calcul.ajouterOperande("3");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_bouton3ActionPerformed

    private void bouton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton4ActionPerformed
        calcul.ajouterOperande("4");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_bouton4ActionPerformed

    private void bouton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton5ActionPerformed
        calcul.ajouterOperande("5");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_bouton5ActionPerformed

    private void bouton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton6ActionPerformed
        calcul.ajouterOperande("6");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_bouton6ActionPerformed

    private void bouton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton7ActionPerformed
        calcul.ajouterOperande("7");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_bouton7ActionPerformed

    private void bouton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton8ActionPerformed
        calcul.ajouterOperande("8");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_bouton8ActionPerformed

    private void bouton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton9ActionPerformed
        calcul.ajouterOperande("9");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_bouton9ActionPerformed

    private void bouton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton0ActionPerformed
        calcul.ajouterOperande("0");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_bouton0ActionPerformed

    private void boutonAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAdditionActionPerformed
        calcul.ajouterOperateur("+");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_boutonAdditionActionPerformed

    private void boutonSoustractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSoustractionActionPerformed
        calcul.ajouterOperateur("-");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_boutonSoustractionActionPerformed

    private void boutonMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonMultiplicationActionPerformed
        calcul.ajouterOperateur("*");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_boutonMultiplicationActionPerformed

    private void boutonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDivisionActionPerformed
        calcul.ajouterOperateur("/");
        textOperation.setText(calcul.affichage());
    }//GEN-LAST:event_boutonDivisionActionPerformed

    /**
     * Fait le calcul
     * Efface l'affichage de l'operation
     * Met a jour l'historique avec le dernier calcul
     * @param evt 
     */
    private void boutonCalculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCalculerActionPerformed
        
        // calcul
        
        try{
            
            //test dabord si le calcul est complet
            validerCalculComplet();
            
            calculateur.calculer(calcul);
 
            //textHistorique.setText(calculateur.afficher());

            // Efface operation

            clear();

            // Met a jour le calcul dans l'historique

            String listeOperations = "";
            String operation = "";

            ArrayList<String> historique = calculateur.getHistorique();
            for(int i=0; i<historique.size();i++){
                listeOperations += historique.get(i) + "\n";
                
            }
            textHistorique.setText(listeOperations);

            System.out.println(listeOperations);

         }catch(CalculIncomplet incomplet){
            
        }
        
    }//GEN-LAST:event_boutonCalculerActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        
        clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void clear(){
        // efface les donnees
        calcul.clear();
        // affiche les pas de donnees
        
        textOperation.setText(calcul.affichage());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton0;
    private javax.swing.JButton bouton1;
    private javax.swing.JButton bouton2;
    private javax.swing.JButton bouton3;
    private javax.swing.JButton bouton4;
    private javax.swing.JButton bouton5;
    private javax.swing.JButton bouton6;
    private javax.swing.JButton bouton7;
    private javax.swing.JButton bouton8;
    private javax.swing.JButton bouton9;
    private javax.swing.JButton boutonAddition;
    private javax.swing.JButton boutonCalculer;
    private javax.swing.JButton boutonDivision;
    private javax.swing.JButton boutonMultiplication;
    private javax.swing.JButton boutonSoustraction;
    private javax.swing.ButtonGroup groupeBoutonOperandes;
    private javax.swing.ButtonGroup groupeBoutonOperations;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHistorique;
    private javax.swing.JLabel labelNomApplication;
    private javax.swing.JTextArea textHistorique;
    private javax.swing.JTextField textOperation;
    // End of variables declaration//GEN-END:variables


private void validerCalculComplet()  throws CalculIncomplet{
        
         if( !calcul.hasOperandeGauche() 
                || !calcul.hasOperandeDroit()
                || !calcul.hasOperateur())
             throw new CalculIncomplet();
    }

}