/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1895248
 */
public class Calculatrice extends javax.swing.JFrame {

    /**
     * Creates new form Calculatrice
     */
    public Calculatrice() {
        initComponents();
    }

    /**
     * Ajoute l'operande si il y a 0 ou 1 operande
     */
    
    public void ajouterOperande(String operande){
        
        //on doit avoir 0 ou 2 caracteres
        int nbrOp = textOperation.getText().length();
        
        System.out.println("ajouterOperande, nbrOp = "+nbrOp);
        
        //cas ayant rien
        if(nbrOp == 0){
            
            //on peut ajouter l'operande en parametre
            textOperation.setText(operande);
        }
        
        //cas ayant un operande et un operateur
        if(nbrOp == 2){
            
            //On lit le contenu
            String contenuActuel = textOperation.getText();
            
            //On met a jour le champ texte
            textOperation.setText(contenuActuel+operande);
        }
    }
    
    /**
     * Ajoute un operateur si il y a un operande
     * @param operateur 
     */
    public void ajouterOperateur(String operateur){
        
        //prend le nombre de caractere
        int nbrOp = textOperation.getText().length();
        
        System.out.println("ajouterOperateur, nbrOp = "+nbrOp);
        
        //On doit avoir un operande
        if(nbrOp == 1){
            
            //on lit le contenu
            String contenuActuel = textOperation.getText();
            
            //on peut ajouter l'operateur en parametre
            textOperation.setText(contenuActuel + operateur);
            
            System.out.println("ajouterOperateur, textOperation = "+contenuActuel + operateur);
        }
    }
    
    /**
     * Calcule le resultat
     * @return Le resultat
     */
    public double calculer(){
        double resultat = 0 ;
        
        //On lit l'operation a faire
        String leCalculAFaire = textOperation.getText();
        
        //On lit l'operande de gauche
        int op1 = Integer.parseInt(leCalculAFaire.substring(0, 1));
        
        //On lit l'operation a faire
        String operateur = leCalculAFaire.substring(1, 2);
        
        //On associe l'operande de droite
        int op2 = Integer.parseInt(leCalculAFaire.substring(2, 3));
        
        //On compare l'operation
        if(operateur.equalsIgnoreCase("+")){
            resultat = op1 + op2;
        }
        if(operateur.equalsIgnoreCase("-")){
            resultat = op1 - op2;
        }
        if(operateur.equalsIgnoreCase("*")){
            resultat = op1 * op2;
        }
        if(operateur.equalsIgnoreCase("/")){
            try{
                resultat = op1 / op2;
            }catch(Exception e){
                System.out.println("Petit snoro, va");
            }
            
        }
        
        return resultat;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupeBoutonOperandes = new javax.swing.ButtonGroup();
        groupeBoutonOperations = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelNomApplication = new javax.swing.JLabel();
        bouton1 = new javax.swing.JButton();
        bouton2 = new javax.swing.JButton();
        bouton3 = new javax.swing.JButton();
        bouton5 = new javax.swing.JButton();
        bouton4 = new javax.swing.JButton();
        bouton6 = new javax.swing.JButton();
        bouton7 = new javax.swing.JButton();
        bouton8 = new javax.swing.JButton();
        bouton9 = new javax.swing.JButton();
        bouton0 = new javax.swing.JButton();
        textHistorique = new javax.swing.JTextField();
        textOperation = new javax.swing.JTextField();
        boutonAddition = new javax.swing.JButton();
        boutonSoustraction = new javax.swing.JButton();
        boutonMultiplication = new javax.swing.JButton();
        boutonDivision = new javax.swing.JButton();
        boutonCalculer = new javax.swing.JButton();
        labelHistorique = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNomApplication.setText("Calculatrice");

        bouton1.setText("1");
        groupeBoutonOperandes.add(bouton1);
        bouton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton1ActionPerformed(evt);
            }
        });

        bouton2.setText("2");
        groupeBoutonOperandes.add(bouton2);
        bouton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton2ActionPerformed(evt);
            }
        });

        bouton3.setText("3");
        groupeBoutonOperandes.add(bouton3);
        bouton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton3ActionPerformed(evt);
            }
        });

        bouton5.setText("5");
        groupeBoutonOperandes.add(bouton5);
        bouton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton5ActionPerformed(evt);
            }
        });

        bouton4.setText("4");
        groupeBoutonOperandes.add(bouton4);
        bouton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton4ActionPerformed(evt);
            }
        });

        bouton6.setText("6");
        groupeBoutonOperandes.add(bouton6);
        bouton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton6ActionPerformed(evt);
            }
        });

        bouton7.setText("7");
        groupeBoutonOperandes.add(bouton7);
        bouton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton7ActionPerformed(evt);
            }
        });

        bouton8.setText("8");
        groupeBoutonOperandes.add(bouton8);
        bouton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton8ActionPerformed(evt);
            }
        });

        bouton9.setText("9");
        groupeBoutonOperandes.add(bouton9);
        bouton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton9ActionPerformed(evt);
            }
        });

        bouton0.setText("0");
        groupeBoutonOperandes.add(bouton0);
        bouton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton0ActionPerformed(evt);
            }
        });

        boutonAddition.setText("+");
        groupeBoutonOperations.add(boutonAddition);
        boutonAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAdditionActionPerformed(evt);
            }
        });

        boutonSoustraction.setText("-");
        groupeBoutonOperations.add(boutonSoustraction);
        boutonSoustraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSoustractionActionPerformed(evt);
            }
        });

        boutonMultiplication.setText("x");
        groupeBoutonOperations.add(boutonMultiplication);
        boutonMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMultiplicationActionPerformed(evt);
            }
        });

        boutonDivision.setText("/");
        groupeBoutonOperations.add(boutonDivision);
        boutonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDivisionActionPerformed(evt);
            }
        });

        boutonCalculer.setText("=");
        boutonCalculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCalculerActionPerformed(evt);
            }
        });

        labelHistorique.setText("Historique opérations");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelNomApplication)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bouton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bouton5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bouton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bouton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bouton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boutonSoustraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bouton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boutonAddition))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(bouton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bouton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bouton9))
                            .addComponent(bouton0)
                            .addComponent(boutonCalculer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boutonDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boutonMultiplication, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                    .addComponent(textOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHistorique)
                    .addComponent(textHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomApplication)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelHistorique)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bouton3)
                            .addComponent(bouton1)
                            .addComponent(bouton2)
                            .addComponent(boutonAddition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bouton5)
                            .addComponent(bouton4)
                            .addComponent(bouton6)
                            .addComponent(boutonSoustraction))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bouton7)
                            .addComponent(bouton8)
                            .addComponent(bouton9)
                            .addComponent(boutonMultiplication))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bouton0)
                            .addComponent(boutonDivision))
                        .addGap(28, 28, 28)
                        .addComponent(boutonCalculer)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addComponent(textHistorique)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton1ActionPerformed
        ajouterOperande("1");
    }//GEN-LAST:event_bouton1ActionPerformed

    private void bouton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton2ActionPerformed
        ajouterOperande("2");
        
    }//GEN-LAST:event_bouton2ActionPerformed

    private void bouton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton3ActionPerformed
        ajouterOperande("3");
    }//GEN-LAST:event_bouton3ActionPerformed

    private void bouton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton4ActionPerformed
        ajouterOperande("4");
    }//GEN-LAST:event_bouton4ActionPerformed

    private void bouton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton5ActionPerformed
        ajouterOperande("5");
    }//GEN-LAST:event_bouton5ActionPerformed

    private void bouton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton6ActionPerformed
        ajouterOperande("6");
    }//GEN-LAST:event_bouton6ActionPerformed

    private void bouton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton7ActionPerformed
        ajouterOperande("7");
    }//GEN-LAST:event_bouton7ActionPerformed

    private void bouton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton8ActionPerformed
        ajouterOperande("8");
    }//GEN-LAST:event_bouton8ActionPerformed

    private void bouton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton9ActionPerformed
        ajouterOperande("9");
    }//GEN-LAST:event_bouton9ActionPerformed

    private void bouton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton0ActionPerformed
        ajouterOperande("0");
    }//GEN-LAST:event_bouton0ActionPerformed

    private void boutonAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAdditionActionPerformed
        ajouterOperateur("+");
    }//GEN-LAST:event_boutonAdditionActionPerformed

    private void boutonSoustractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSoustractionActionPerformed
        ajouterOperateur("-");
    }//GEN-LAST:event_boutonSoustractionActionPerformed

    private void boutonMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonMultiplicationActionPerformed
        ajouterOperateur("*");
    }//GEN-LAST:event_boutonMultiplicationActionPerformed

    private void boutonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDivisionActionPerformed
        ajouterOperateur("/");
    }//GEN-LAST:event_boutonDivisionActionPerformed

    private void boutonCalculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCalculerActionPerformed
        
        //lit historique
        String historique = textHistorique.getText();
        
        //calcul nouvelle operation
        String newCalcul = String.valueOf(calculer());
        
        //concatene historique (new line ne fonctionne pas)
        //todo: fix this newline
        textHistorique.setText(historique + '\n' + newCalcul);
        
        //reset champ calcul
        textOperation.setText("");
    }//GEN-LAST:event_boutonCalculerActionPerformed

    private void groupeBoutonOperandesActionPerformed(java.awt.event.ActionEvent evt) {                                        
        //obtenir une reference sur le bouton qui a ete enfonce
        //lire son label
        //mettre a jour le champ textOperation
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton0;
    private javax.swing.JButton bouton1;
    private javax.swing.JButton bouton2;
    private javax.swing.JButton bouton3;
    private javax.swing.JButton bouton4;
    private javax.swing.JButton bouton5;
    private javax.swing.JButton bouton6;
    private javax.swing.JButton bouton7;
    private javax.swing.JButton bouton8;
    private javax.swing.JButton bouton9;
    private javax.swing.JButton boutonAddition;
    private javax.swing.JButton boutonCalculer;
    private javax.swing.JButton boutonDivision;
    private javax.swing.JButton boutonMultiplication;
    private javax.swing.JButton boutonSoustraction;
    private javax.swing.ButtonGroup groupeBoutonOperandes;
    private javax.swing.ButtonGroup groupeBoutonOperations;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHistorique;
    private javax.swing.JLabel labelNomApplication;
    private javax.swing.JTextField textHistorique;
    private javax.swing.JTextField textOperation;
    // End of variables declaration//GEN-END:variables
}
